# Generated by Django 5.0.6 on 2024-06-01 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_marka', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_model', models.CharField(max_length=16, unique=True)),
                ('marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_store.marka')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_car', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripto', models.TextField()),
                ('date', models.DateField()),
                ('year', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_store.category')),
                ('markal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_store.marka')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_store.model')),
            ],
        ),
    ]
